paths:
  raw:
    metropt: data/raw/MetroPT3(AirCompressor).csv
    metropt3: data/raw/MetroPT3(AirCompressor).csv
  processed:
    x_train_baseline: data/processed/x_train_baseline.csv
    y_train_baseline: data/processed/y_train_baseline.csv
    x_test_baseline: data/processed/x_test_baseline.csv
    y_test_baseline: data/processed/y_test_baseline.csv
    scaler_baseline: data/processed/scaler_baseline.pkl
    X_train_bilstm: X_train_bilstm.joblib
    y_train_bilstm: y_train_bilstm.joblib
    X_test_bilstm: X_test_bilstm.joblib
    y_test_bilstm: y_test_bilstm.joblib
    scaler_x_bilstm: scaler_x_bilstm.joblib
    scaler_y_bilstm: scaler_y_bilstm.joblib
bilstm:
  test_size: 0.2
  random_state: 42